worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    # 重定向所有 HTTP 请求到 HTTPS
    server {
        listen 80;
        listen [::]:80;
        server_name fcbyk.com www.fcbyk.com;

        return 301 https://$host$request_uri;
    }

    # 配置 HTTPS 服务器块
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name fcbyk.com www.fcbyk.com;

        # SSL 相关配置
        ssl_certificate certs/fcbyk.com.pem;
        ssl_certificate_key certs/fcbyk.com.key;

        # SSL 配置，增强安全性
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # 配置静态文件的根目录
        root .;

        # 配置首页
        index index.html;

        # 处理所有请求
        location . {
            try_files $uri $uri/ =404;
        }
    }
}
