worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
        listen 80;
        listen [::]:80;
        server_name fcbyk.com;

        # 重定向到 HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name fcbyk.com;

        # SSL 相关配置
        ssl_certificate certs/fcbyk.com.pem;
        ssl_certificate_key certs/fcbyk.com.key;

        # 配置静态文件的根目录
        root /;

        # 配置首页
        index index.html;

        # 处理所有请求
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
