const fs = require('fs');
const path = require('path');

// 目标目录路径（src/utils）
const utilsDir = path.join(__dirname, '../src/utils');

// 读取所有 .ts 文件（排除 index.ts 和测试文件）
const files = fs.readdirSync(utilsDir)
    .filter(file =>
        file.endsWith('.ts') &&
        file !== 'index.ts' &&
        !file.endsWith('.test.ts')
    );

// 生成导出语句
const exportStatements = files.map(file => {
    const name = file.replace('.ts', '');
    return `export * from './${name}';`;
});

// 写入 index.ts
fs.writeFileSync(
    path.join(utilsDir, 'index.ts'),
    '// Auto-generated by scripts/generate-exports.js\n' +
    exportStatements.join('\n') + '\n'
);

console.log('🎉 src/utils/index.ts 已自动生成！');